### PR TITLE
optimize dockerfile, added supervisord, enhance entrypoint script

### PR DESCRIPTION
**Pull request by kuzi-moto**
Here are some changes I've been working on for some time. To list it out:

- Optimize Dockerfile - Lots of redundant steps removed, incorporated multi-stage build to 'build' the Ampache source, **huge** reduction in image size, from 1,286 MB to 836 MB. 
- Added docker-compose instructions, along with a sample `docker-compose.yml` file.
- Make general installation steps more verbose and explicit.
- Added `docker-entrypoint.sh` script to help with permissions issues (this is still somewhat in testing).
- Added supervisord to run MySQL, Apache, cron, and the inotifywatch script (which has been split out into its own file). I added this because I believe it handles starting/stopping the processes more gracefully than did the previous method, and each of those processes' status is viewable in the container's output.

I wanted some others to do some testing to ensure that no functionality was lost, and everything still works the same way. Additionally, the permissions stuff still needs some more testing out, but I wanted this available for others to poke at.

### CODE REVIEW

**Comment by lachlan-00** [comment]
ohh, this is looking pretty

**Comment by kuzi-moto** [comment]
Additionally, I was going to ask if there is a reason we include an Ampache config file in the image? Seems a bit redundant if it's coming with the Ampache source anyway.

**Comment by lachlan-00** [comment]
I think it's so people can roll their own images from git.

**Comment by lachlan-00** [comment]
needs a little more work, the mysql service doesn't start from what i can tell i'll tweak and see what's missing,

really like all this though.

**Comment by kuzi-moto** [comment]
Odd, I just built it and everything seemed to be working. I suppose that makes sense, though I like the idea of incorporating all the config options as environment variables. Not sure how to incorporate that though. And thanks!

**Comment by lachlan-00** [comment]
i think the volumes are screwing up for me i get perm errors for /var/lib/mysql
image

**Comment by lachlan-00** [comment]
might actually just be the initial mysqld command, testing out now. 

so glad we don't have to rebuild the entire thing ever time

**Comment by lachlan-00** [comment]
There we go @kuzi-moto i was running off a zip but had to clone instead from your repo.

not sure why it all was permission denied though, really weird so i'll try and break it some more.

**Comment by lachlan-00** [comment]
okay! going to merge this and update all 3 at the same time after 4.2.2 (another week)

for ampache 5.0.0 i want to move all these off ubuntu1804 to something like debian stable which is what i did the nosql tag on.

This is a good change and i'll just tweak nosql and develop this week to make it ready in time

**Comment by lachlan-00** [comment]
@kuzi-moto i shoehorned your work a bit in develop and nosql but i think it can probably be slimmed down a bit more.

I'm going to load up an image and see what else i can uninstall from the debian image but then it'll go into master after 4.2.2.

Really impressive effort here i'll put you up in the readme with the other acknowledgements. :)

**Pull request merged**
