### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by arielelkin**
checks if ampache image builds and runs properly. 

to be merged after https://github.com/ampache/ampache-docker/pull/8 is reviewed.

don't forget to switch on Travis CI for https://travis-ci.org/ampache/ampache-docker

### CODE REVIEW

**Comment by arielelkin** [comment]
@Afterster bump 🙂

**Comment by Afterster** [comment]
Thanks @arielelkin !
Sorry for the delay but could you clean your git history? Also, why changing the version from master to a specific release (duplicate with #8 btw)? master should be last release according to ampache developing convention.

**Comment by arielelkin** [comment]
This is a bad habit of mine.. It goes like this: I create a git branch out of the branch I am working from (my local `master` instead of upstream's) and make my changes on it. I realise my mistake as I submit the PR, but instead of cleaning up locally, I ask for the first PR to be reviewed first (as I did). Then when you'd merge that PR, I'd merge upstream `master` into the second PR and it looks clean again...

Bad habit. Sorry. 

It's clean now. This PR no longer depends on https://github.com/ampache/ampache-docker/pull/8. 

I've also squashed all the other commits.

**Comment by arielelkin** [comment]
@Afterster bump 🙂

**Comment by arielelkin** [comment]
@Afterster bump  🙂 🙂

**Comment by arielelkin** [comment]
closing due to unresponsiveness. [see discussion](https://groups.google.com/d/msg/ampache/aMGf6bszVgs/ne3828ZPBgAJ).

**Pull request closed without merging**
