### PR TITLE
fix bug that didn't install latest version

### PR DESCRIPTION
**Pull request by arielelkin**
addresses https://github.com/ampache/ampache-docker/issues/6

### CODE REVIEW

**Comment by Afterster** [comment]
I'm not sure about your PR, it doesn't seem complete. You still extract from /opt/master.tar.gz which doesn't exist anymore with your changes.

**Comment by arielelkin** [comment]
I was just passing on the changes suggested by @evil666 in the issue: https://github.com/ampache/ampache-docker/issues/6#issuecomment-239049945

But you're right, that change doesn't fix the issue. 

I've tried to `docker run` the ampache image locally, and I get this update screen after Step 3 of the install: 

image

But I don't get this option to update when I install on my server. Are you able to reproduce this? 

The Dockerfile pulls https://github.com/ampache/ampache/archive/master.tar.gz, which is `git HEAD`. 

Is this the tarball of the correct version?

**Comment by icebal** [comment]
you also need to change the following line to ampache-master.tar.gz so it can actually unpack it:
    tar -C /var/www -xf /opt/master.tar.gz ampache-master --strip=1 && \
needs to be
    tar -C /var/www -xf /opt/apmache-master.tar.gz ampache-master --strip=1 && \

**Comment by Kernald** [comment]
Maybe using a direct link to the latest release (https://github.com/ampache/ampache/releases/download/3.8.2/ampache-3.8.2_all.zip for example) would be safer, wouldn't it? Additionally, specific tagged versions could be pushed to Docker Hub.

**Comment by arielelkin** [comment]
OK, I think the issue was due to the fact that I wasn't extracting from the correct place. This now pulls and installs straight from https://github.com/ampache/ampache/archive/master.tar.gz, i.e. whatever is at `git HEAD` 

I've tested it and it correctly installs v3.8.2 

Please let me know if there's anything else needed to merge this.

**Comment by arielelkin** [comment]
@Afterster 

Please let me know if there's anything else needed to merge this :-)

**Comment by Afterster** [comment]
I agree with @Kernald but I'm gonna merge it as it address the original issue. Thanks!

**Pull request merged**
